rules: |
    We have very simple rules
    Don't ruin other peoples fun
    No bigotry, no cheating, no hacking
help: |
    Type /rules to get the rules of the server.
    Type /worldguardhelp for help with worldguarding!
    Type /trust for help with getting trusted!
intro: |
    Kill babies
    Fry and eat them
repeatmessages: |
    Visit our community: http://forums.joe.to
    Donors can always join. http://donate.joe.to
worldguardhelp: |
    To get your area protected and free from griefers, mark opposite corners with orange wool and then, when standing at one of your orange pillars, type /report worldguard What you want your building to be called.
    If you'd like to see if the area you are in is protected, right-click it with string in your hand. 
    If you'd like to add members to your worldguard region, type /region addmember Region name member name. 
motd: |
    Welcome to joe.to
    Please read our rules at /rules