name: J2MC_Info
main: to.joe.j2mc.info.J2MC_Info
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Information module
commands:
  help:
    description: help!
    usage: /help
  intro:
    description: gives a basic intro
    usage: /intro
  rules:
    description: give me the rules.
    usage: /help
  reloadinfo:
    description: reloads data from config.yml
    usage: /reloadinfo
  worldguardhelp:
    description: gives some basic protection help
    usage: /wordguardhelp
permissions:
  j2mc.info.reload:
    descriptions: gives access to /reloadinfo
